using System;
using System.IO;
using System.IO.Compression;
using System.Net;
using System.Net.Http;
using System.Linq;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Security.Cryptography;
using System.Threading;
using System.Threading.Tasks;
using System.Drawing;
using System.Windows.Forms;
using System.Web.Script.Serialization;
using System.Diagnostics;
internal static class Setup {
 [System.Runtime.InteropServices.DllImport("shell32.dll")]static extern int SHGetKnownFolderPath([System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.LPStruct)]Guid id,uint flags,IntPtr token,out IntPtr path);
 internal static string PluginFolder(){string custom=Arg("--plugin-dir");if(custom!=null)return custom;IntPtr path;int result=SHGetKnownFolderPath(new Guid("374DE290-123F-4565-9164-39C4925E467B"),0,IntPtr.Zero,out path);if(result!=0)throw new IOException("无法找到下载文件夹 / Downloads folder unavailable");try{return Path.Combine(System.Runtime.InteropServices.Marshal.PtrToStringUni(path),"Paper Voice");}finally{System.Runtime.InteropServices.Marshal.FreeCoTaskMem(path);}}
 internal static JavaScriptSerializer JSON=new JavaScriptSerializer {MaxJsonLength=4000000};
 internal static Dictionary<string,object> Config=Parse(Resource("installer.json")),Runtime=(Dictionary<string,object>)Config["runtime"];
 internal static List<Dictionary<string,object>> Packages=Rows(Runtime["packages"]);
 internal static string AppData=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"Zotero","Zotero"),Pointer=Path.Combine(AppData,"paper-voice-location.json");
 internal static string Arg(string k){var a=Environment.GetCommandLineArgs();int i=Array.IndexOf(a,k);return i>=0&&i+1<a.Length?a[i+1]:null;}
 internal static bool Flag(string k){return Environment.GetCommandLineArgs().Contains(k);}
 internal static Dictionary<string,object> Parse(string s){return JSON.Deserialize<Dictionary<string,object>>(s);}
 internal static List<Dictionary<string,object>> Rows(object v){return ((IEnumerable)v).Cast<object>().Select(x=>(Dictionary<string,object>)x).ToList();}
 internal static string Resource(string n){using(var s=new StreamReader(Assembly.GetExecutingAssembly().GetManifestResourceStream(n)))return s.ReadToEnd();}
 internal static string Hash(string path){using(var f=File.OpenRead(path))using(var h=SHA256.Create())return BitConverter.ToString(h.ComputeHash(f)).Replace("-","").ToLowerInvariant();}
 internal static bool Valid(string path,Dictionary<string,object> a){return File.Exists(path)&&new FileInfo(path).Length==Convert.ToInt64(a["bytes"])&&Hash(path)==(string)a["sha256"];}
 internal static string DefaultRoot(){try{var j=Parse(File.ReadAllText(Pointer));var path=(string)j["root"];if(Path.IsPathRooted(path))return path;}catch(Exception){}return Path.Combine(AppData,"paper-voice-engine");}
 internal static string Quote(string v){return "\""+v.Replace("\"","\\\"")+"\"";}
 [STAThread] static int Main(){ServicePointManager.SecurityProtocol=SecurityProtocolType.Tls12;try{if(Arg("--zotero-action")!=null){string operation=Arg("--zotero-action");object result;if(operation=="discover")result=new{profiles=ZoteroInstall.Profiles(Arg("--profile-base")).Select(p=>new{name=p.Name,path=p.Path}).ToArray(),applications=ZoteroInstall.Applications()};else{var asset=(Dictionary<string,object>)Config["plugin"];string profile=Arg("--profile"),version=(string)Config["version"],digest=(string)asset["sha256"];result=new{state=operation=="stage"?ZoteroInstall.Stage(Arg("--xpi"),profile,version,digest,Arg("--backup-dir")):ZoteroInstall.Status(profile,version,digest)};}File.WriteAllText(Arg("--result"),JSON.Serialize(result));return 0;}if(Flag("--quiet")){if(Arg("--destination")==null||Arg("--download-dir")==null||Arg("--pointer")==null||Arg("--plugin-dir")==null)throw new Exception("Explicit test directories required");using(var e=new Engine()){if(Flag("--cancel-test"))e.Progress=(p,v)=>{if((p=="runtime"||p=="voices")&&v>0)e.Cancel();};var xpi=e.Install(Arg("--destination"),Arg("--download-dir"),Arg("--pointer"),Flag("--plugin-only")).GetAwaiter().GetResult();if(Arg("--result")!=null)File.WriteAllText(Arg("--result"),xpi);return 0;}}Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.Run(new Installer());return 0;}catch(Exception e){if(Arg("--result")!=null)File.WriteAllText(Arg("--result"),e.ToString());return 1;}}
}
internal sealed class Engine:IDisposable {
 readonly CancellationTokenSource stop=new CancellationTokenSource();internal Action<string,double> Progress;internal bool Committing;internal bool Cancelled{get{return stop.IsCancellationRequested;}}internal void Cancel(){if(!Committing)stop.Cancel();}public void Dispose(){stop.Dispose();}
 void Check(){stop.Token.ThrowIfCancellationRequested();}void Report(string p,double v){Check();if(Progress!=null)Progress(p,v);}
 void Verify(string root){var files=Setup.Rows(Setup.Runtime["files"]);for(int i=0;i<files.Count;i++){Check();var f=files[i];if(!Setup.Valid(Path.Combine(root,((string)f["name"]).Replace('/',Path.DirectorySeparatorChar)),f))throw new Exception("声音文件不完整 / Incomplete voices");if(i%40==0)Report("verify",(double)i/files.Count);}}
 async Task<string> Fetch(Dictionary<string,object> a,string cache,string phase,double before,double total){Check();string path=Path.Combine(cache,(string)a["name"]);long size=Convert.ToInt64(a["bytes"]);if(Setup.Valid(path,a)){Report(phase,(before+size)/total);return path;}string temp=Path.Combine(cache,".download-"+Guid.NewGuid().ToString("N"));try{
  string offline=Setup.Arg("--package-dir");if(offline!=null){File.Copy(Path.Combine(offline,(string)a["name"]),temp);Report(phase,(before+size)/total);}else{
   var uri=new Uri((string)a["url"]);using(var handler=new HttpClientHandler{AllowAutoRedirect=false})using(var client=new HttpClient(handler))using(var timeout=CancellationTokenSource.CreateLinkedTokenSource(stop.Token)){timeout.CancelAfter(TimeSpan.FromMinutes(10));client.Timeout=TimeSpan.FromMinutes(10);HttpResponseMessage response=null;try{for(int i=0;i<8;i++){if(uri.Scheme!="https")throw new Exception("HTTPS required");response=await client.GetAsync(uri,HttpCompletionOption.ResponseHeadersRead,timeout.Token);if((int)response.StatusCode<300||(int)response.StatusCode>=400)break;var next=response.Headers.Location;if(next==null)throw new Exception("Missing redirect");uri=next.IsAbsoluteUri?next:new Uri(uri,next);response.Dispose();response=null;}if(response==null||response.StatusCode!=HttpStatusCode.OK)throw new Exception("下载暂不可用 / Download unavailable");using(var input=await response.Content.ReadAsStreamAsync())using(var output=File.Create(temp)){byte[] b=new byte[65536];long read=0;int count;while((count=await input.ReadAsync(b,0,b.Length,timeout.Token))>0){read+=count;if(read>size)throw new Exception("Unexpected file size");await output.WriteAsync(b,0,count,timeout.Token);Report(phase,(before+read)/total);}}}finally{if(response!=null)response.Dispose();}}
  }Check();if(!Setup.Valid(temp,a))throw new Exception("下载校验失败 / Download verification failed");if(File.Exists(path))File.Replace(temp,path,null);else File.Move(temp,path);return path;
 }finally{if(File.Exists(temp))File.Delete(temp);}}
 void Extract(string archive,string root){var prefix=Path.GetFullPath(root)+Path.DirectorySeparatorChar;using(var z=ZipFile.OpenRead(archive)){foreach(var entry in z.Entries){Check();var name=entry.FullName.Replace('/',Path.DirectorySeparatorChar);var dest=Path.GetFullPath(Path.Combine(root,name));if(!dest.StartsWith(prefix,StringComparison.OrdinalIgnoreCase)||name.Contains(":"))throw new Exception("Invalid archive path");Directory.CreateDirectory(Path.GetDirectoryName(dest));if(!entry.FullName.EndsWith("/"))entry.ExtractToFile(dest,true);}}}
 async Task Run(string exe,IEnumerable<string> args){var info=new ProcessStartInfo(exe,string.Join(" ",args.Select(Setup.Quote))){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true,StandardOutputEncoding=Encoding.UTF8,StandardErrorEncoding=Encoding.UTF8};info.EnvironmentVariables["HF_HUB_OFFLINE"]="1";using(var p=Process.Start(info)){var o=p.StandardOutput.ReadToEndAsync();var e=p.StandardError.ReadToEndAsync();await Task.Run(()=>p.WaitForExit());var text=await o+await e;if(p.ExitCode!=0)throw new Exception(text);}}
 string ExportPlugin(string source,Dictionary<string,object> asset){string folder=Setup.PluginFolder();Directory.CreateDirectory(folder);string target=Path.Combine(folder,Path.GetFileName(source));if(Setup.Valid(target,asset))return target;string temp=Path.Combine(folder,".paper-voice-"+Guid.NewGuid().ToString("N"));try{File.Copy(source,temp);if(File.Exists(target))File.Replace(temp,target,null);else File.Move(temp,target);return target;}finally{if(File.Exists(temp))File.Delete(temp);}}
 internal async Task<string> Install(string root,string cache,string pointer,bool pluginOnly){Directory.CreateDirectory(cache);var plugin=(Dictionary<string,object>)Setup.Config["plugin"];Report("plugin",0);string cached=await Fetch(plugin,cache,"plugin",0,Convert.ToDouble(plugin["bytes"]));string xpi=ExportPlugin(cached,plugin);Report("pluginDone",1);if(pluginOnly)return xpi;
  root=Path.GetFullPath(root);if(Path.GetFileName(root)!="paper-voice-engine")throw new Exception("Choose a voice folder");Directory.CreateDirectory(Path.GetDirectoryName(root));bool reusable=false;Report("verify",0);try{Verify(root);reusable=true;}catch(Exception){Check();}
  string work=Path.Combine(Path.GetDirectoryName(root),".paper-voice-setup-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(work);try{
   if(!reusable){foreach(var a in Setup.Packages.AsEnumerable().Reverse()){string phase=((string)a["name"]).StartsWith("runtime")?"runtime":"voices",archive=Path.Combine(work,(string)a["name"]);double done=0,total=Convert.ToDouble(a["bytes"]);using(var output=File.Create(archive)){foreach(var part in Setup.Rows(a["parts"])){string file=await Fetch(part,cache,phase,done,total);using(var input=File.OpenRead(file))input.CopyTo(output);done+=Convert.ToDouble(part["bytes"]);}}if(!Setup.Valid(archive,a))throw new Exception("Archive verification failed");Report(phase+"Extract",1);Extract(archive,work);File.Delete(archive);Report(phase+"Done",1);}Verify(Path.Combine(work,"engine"));}else Report("reused",1);
   Check();Committing=true;Report("setup",0);string source=reusable?root:Path.Combine(work,"engine"),script=Path.Combine(work,"commit_runtime.py");File.WriteAllText(script,Setup.Resource("commit_runtime.py"),new UTF8Encoding(false));var args=new List<string>{"-E","-s","-B","-X","utf8",script,"--source",source,"--destination",root,"--pointer",pointer,"--runtime-id",(string)Setup.Runtime["id"]};if(reusable)args.Add("--reuse");await Run(Path.Combine(source,"python","python.exe"),args);Report("ready",1);return xpi;
  }finally{try{Directory.Delete(work,true);}catch(IOException){}}
 }
}
internal static class Visual {
 internal static readonly Dictionary<string,object> Appearance=ReadAppearance();
 static Dictionary<string,object> ReadAppearance(){using(var stream=Assembly.GetExecutingAssembly().GetManifestResourceStream("appearance.json"))using(var reader=new StreamReader(stream))return new System.Web.Script.Serialization.JavaScriptSerializer().Deserialize<Dictionary<string,object>>(reader.ReadToEnd());}
 internal static Color ColorFor(string key){return ColorTranslator.FromHtml("#"+((Dictionary<string,object>)Appearance["colors"])[key]);}
 internal static readonly Color Ink=ColorFor("ink"),Muted=ColorFor("muted"),Green=ColorFor("success"),Paper=ColorFor("paper");
 static readonly Dictionary<string,System.Drawing.Text.PrivateFontCollection> Fonts=new Dictionary<string,System.Drawing.Text.PrivateFontCollection>();
 [System.Runtime.InteropServices.DllImport("gdi32.dll")]static extern IntPtr AddFontMemResourceEx(IntPtr p,uint size,IntPtr reserved,ref uint count);
 [System.Runtime.InteropServices.DllImport("gdi32.dll")]static extern IntPtr CreateCompatibleDC(IntPtr dc);
 [System.Runtime.InteropServices.DllImport("gdi32.dll")]static extern IntPtr SelectObject(IntPtr dc,IntPtr obj);
 [System.Runtime.InteropServices.DllImport("gdi32.dll",CharSet=System.Runtime.InteropServices.CharSet.Unicode)]static extern uint GetGlyphIndicesW(IntPtr dc,string text,int count,[System.Runtime.InteropServices.Out]ushort[] glyphs,uint flags);
 [System.Runtime.InteropServices.DllImport("gdi32.dll")]static extern bool DeleteObject(IntPtr obj);
 [System.Runtime.InteropServices.DllImport("gdi32.dll")]static extern bool DeleteDC(IntPtr dc);
 static Visual(){foreach(var name in new[]{"VoiceSans-Regular.ttf.deflate","VoiceSans-SemiBold.ttf.deflate"})using(var s=Assembly.GetExecutingAssembly().GetManifestResourceStream(name))using(var unzip=new DeflateStream(s,CompressionMode.Decompress))using(var memory=new MemoryStream()){unzip.CopyTo(memory);var bytes=memory.ToArray();var p=System.Runtime.InteropServices.Marshal.AllocHGlobal(bytes.Length);System.Runtime.InteropServices.Marshal.Copy(bytes,0,p,bytes.Length);var collection=new System.Drawing.Text.PrivateFontCollection();collection.AddMemoryFont(p,bytes.Length);Fonts[name]=collection;uint count=0;if(AddFontMemResourceEx(p,(uint)bytes.Length,IntPtr.Zero,ref count)==IntPtr.Zero)throw new Exception("Bundled font registration failed");}}
 internal static Font Font(float size,FontStyle weight=FontStyle.Regular){var collection=Fonts[weight==FontStyle.Bold?"VoiceSans-SemiBold.ttf.deflate":"VoiceSans-Regular.ttf.deflate"];var family=collection.Families.Single();var style=family.IsStyleAvailable(FontStyle.Regular)?FontStyle.Regular:FontStyle.Bold;return new Font(family,size,style,GraphicsUnit.Pixel);}
 internal static bool Covered(Font font,string text){IntPtr dc=CreateCompatibleDC(IntPtr.Zero),handle=font.ToHfont(),old=SelectObject(dc,handle);try{var glyphs=new ushort[text.Length];return GetGlyphIndicesW(dc,text,text.Length,glyphs,1)!=uint.MaxValue&&glyphs.All(x=>x!=0xffff&&x!=0);}finally{SelectObject(dc,old);DeleteObject(handle);DeleteDC(dc);}}
 internal static System.Drawing.Drawing2D.GraphicsPath Round(RectangleF r,float radius){var p=new System.Drawing.Drawing2D.GraphicsPath();float d=radius*2;p.AddArc(r.X,r.Y,d,d,180,90);p.AddArc(r.Right-d,r.Y,d,d,270,90);p.AddArc(r.Right-d,r.Bottom-d,d,d,0,90);p.AddArc(r.X,r.Bottom-d,d,d,90,90);p.CloseFigure();return p;}
 internal static void DrawText(Graphics g,string text,Font font,Rectangle bounds,Color color,bool center=false,bool path=false){g.TextRenderingHint=System.Drawing.Text.TextRenderingHint.AntiAliasGridFit;using(var brush=new SolidBrush(color))using(var format=new StringFormat(StringFormat.GenericTypographic)){format.Alignment=center?StringAlignment.Center:StringAlignment.Near;format.LineAlignment=StringAlignment.Center;format.Trimming=path?StringTrimming.EllipsisPath:StringTrimming.EllipsisCharacter;format.FormatFlags|=StringFormatFlags.NoWrap;g.DrawString(text,font,brush,bounds,format);}}
}
internal sealed class Card:Panel {protected override void OnPaintBackground(PaintEventArgs e){e.Graphics.Clear(Visual.Paper);e.Graphics.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;using(var p=Visual.Round(new RectangleF(.5f,.5f,Width-1,Height-1),12))using(var b=new SolidBrush(Color.White))using(var pen=new Pen(Visual.ColorFor("line"),1)){e.Graphics.FillPath(b,p);e.Graphics.DrawPath(pen,p);}}internal Card(){BackColor=Color.White;}}
internal sealed class QuietButton:Button {bool hover;internal QuietButton(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);FlatStyle=FlatStyle.Flat;FlatAppearance.BorderSize=0;UseMnemonic=false;MouseEnter+=(s,e)=>{hover=true;Invalidate();};MouseLeave+=(s,e)=>{hover=false;Invalidate();};}protected override void OnPaintBackground(PaintEventArgs e){e.Graphics.Clear(Visual.Paper);}protected override void OnPaint(PaintEventArgs e){e.Graphics.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;bool primary=BackColor==Visual.ColorFor("accent");var bg=!Enabled?Visual.ColorFor("disabled"):hover?Visual.ColorFor(primary?"primaryHover":"hover"):BackColor;using(var p=Visual.Round(new RectangleF(0,0,Width,Height),9))using(var brush=new SolidBrush(bg))e.Graphics.FillPath(brush,p);if(Focused&&ShowFocusCues)using(var ring=Visual.Round(new RectangleF(2,2,Width-4,Height-4),7))using(var pen=new Pen(Color.FromArgb(153,Visual.ColorFor("accent")),1))e.Graphics.DrawPath(pen,ring);Visual.DrawText(e.Graphics,Text,Font,new Rectangle(6,0,Width-12,Height),Enabled?ForeColor:Visual.ColorFor("disabledInk"),true);}}
internal sealed class Track:Control {double value;internal Color Tint=Visual.Ink;internal double Value{get{return value;}set{this.value=Math.Max(0,Math.Min(1,value));Invalidate();}}internal Track(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);}protected override void OnPaint(PaintEventArgs e){e.Graphics.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;using(var p=Visual.Round(new RectangleF(0,0,Width,Height),Height/2f))using(var b=new SolidBrush(Visual.ColorFor("track")))e.Graphics.FillPath(b,p);if(value>0)using(var p=Visual.Round(new RectangleF(0,0,Math.Max(Height,(float)(Width*value)),Height),Height/2f))using(var b=new SolidBrush(Tint))e.Graphics.FillPath(b,p);}}
internal sealed class SmoothLabel:Label {protected override void OnPaint(PaintEventArgs e){e.Graphics.TextRenderingHint=System.Drawing.Text.TextRenderingHint.AntiAliasGridFit;base.OnPaint(e);}}
internal sealed class PathDisplay:Control {internal PathDisplay(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);}protected override void OnPaint(PaintEventArgs e){Visual.DrawText(e.Graphics,Text,Font,ClientRectangle,Visual.Muted,false,true);}}
internal sealed class Installer:Form{
 string zoteroApp,pluginState="";ZoteroProfile zoteroProfile;bool didStage;System.Windows.Forms.Timer pluginTimer;
 bool zh=(Setup.Arg("--lang")??System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName)=="zh",busy,complete;string root=Setup.Arg("--preview-path")??Setup.DefaultRoot(),xpi;Engine engine;Label heading,intro,status,target;PathDisplay path;Button action,only,browse,cancel,help;Button language;List<Label> titles=new List<Label>(),details=new List<Label>(),badges=new List<Label>();List<Track> bars=new List<Track>();Color accent=Visual.ColorFor("accent");
 string T(string cn,string en){return zh?cn:en;}
 Label TextAt(string text,float size,bool bold,int x,int y,int w,int h){var l=new SmoothLabel{Text=text,UseMnemonic=false,UseCompatibleTextRendering=true,Font=Visual.Font(size,bold?FontStyle.Bold:FontStyle.Regular),Location=new Point(x,y),Size=new Size(w,h),ForeColor=Visual.Ink,BackColor=Color.Transparent};Controls.Add(l);return l;}
 Button ButtonAt(int x,int y,int w,EventHandler click){var b=new QuietButton{Location=new Point(x,y),Size=new Size(w,34),BackColor=Color.White,ForeColor=Visual.Ink,Font=Visual.Font(11,FontStyle.Bold),Cursor=Cursors.Hand};Controls.Add(b);b.Click+=click;return b;}
 void RefreshText(){Text=T("Paper Voice 安装助手","Paper Voice Installer");heading.Text=T("让论文，读给你听。","Make room for listening.");intro.Text=T("按需下载。装好声音后，日常听读无需联网。","Download once. Listen offline, every day.");string[] names={T("Zotero 插件","Zotero plugin"),T("声音引擎","Voice engine"),T("多语言声音","Multilingual voices")},descs={T("自动识别 Zotero，安装听读与翻译","Detect Zotero and set up the plugin"),T("为当前电脑准备本地运行环境","Local runtime for this computer"),T("英语 · 中文 · 日语 · 法语","English · Chinese · Japanese · French")};var assets=new[]{(Dictionary<string,object>)Setup.Config["plugin"],Setup.Packages[1],Setup.Packages[0]};for(int i=0;i<3;i++){titles[i].Text=names[i];details[i].Text=descs[i];badges[i].Text=string.Format("{0:F1} MB",Convert.ToDouble(assets[i]["bytes"])/1e6);}language.Text=zh?"English":"简体中文";target.Text=T("声音位置","Voice folder");path.Text=root.Replace(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"%USERPROFILE%");browse.Text=T("选择文件夹","Browse");help.Text=T("帮助","Help");only.Text=T("仅更新插件","Plugin only");cancel.Text=T("取消","Cancel");action.Text=complete?T("查看插件文件","Show plugin file"):T("下载并安装","Download & install");status.Text=T("已有声音会先检查并复用，不重复下载。","Existing voices are checked and reused.");if(complete)RefreshPluginUI();}
 internal Installer(){AutoScaleDimensions=new SizeF(96,96);AutoScaleMode=AutoScaleMode.Dpi;ClientSize=new Size(640,510);FormBorderStyle=FormBorderStyle.FixedSingle;MaximizeBox=false;StartPosition=FormStartPosition.CenterScreen;BackColor=Visual.Paper;Font=Visual.Font(11);Icon=Icon.ExtractAssociatedIcon(Application.ExecutablePath);TextAt("PAPER VOICE  /  FOR ZOTERO",10,true,30,20,440,18);heading=TextAt("",24,true,30,46,490,42);intro=TextAt("",11,false,32,94,540,24);intro.ForeColor=Visual.Muted;using(var s=Assembly.GetExecutingAssembly().GetManifestResourceStream("mascot.png")){Controls.Add(new PictureBox{Image=new Bitmap(s),Location=new Point(541,23),Size=new Size(72,80),SizeMode=PictureBoxSizeMode.Zoom});}
 for(int i=0;i<3;i++){int y=135+i*70;var card=new Card{Location=new Point(30,y),Size=new Size(580,62)};Controls.Add(card);var number=TextAt((i+1).ToString("00"),11,true,46,y+12,30,20);number.ForeColor=accent;titles.Add(TextAt("",13,true,82,y+8,360,23));var detail=TextAt("",11,false,82,y+33,455,20);detail.ForeColor=Visual.Muted;details.Add(detail);var badge=TextAt("",10,false,509,y+10,85,20);badge.TextAlign=ContentAlignment.TopRight;badge.ForeColor=Visual.Muted;badges.Add(badge);foreach(var l in new[]{number,titles[i],detail,badge}){l.BackColor=Color.White;var local=new Point(l.Left-card.Left,l.Top-card.Top);card.Controls.Add(l);l.Location=local;}var bar=new Track{Location=new Point(82,y+56),Size=new Size(512,3),Tint=accent};card.Controls.Add(bar);bar.Location=new Point(52,56);bars.Add(bar);}
 target=TextAt("",11,true,34,357,85,23);path=new PathDisplay{Location=new Point(120,356),Size=new Size(367,25),Font=Visual.Font(12)};Controls.Add(path);browse=ButtonAt(493,351,117,(s,e)=>{if(complete){ChooseProfile();return;}using(var d=new FolderBrowserDialog{SelectedPath=Directory.Exists(root)?root:Path.GetDirectoryName(root)})if(d.ShowDialog()==DialogResult.OK){root=Path.GetFileName(d.SelectedPath)=="paper-voice-engine"?d.SelectedPath:Path.Combine(d.SelectedPath,"paper-voice-engine");complete=false;RefreshText();}});status=TextAt("",11,false,34,394,572,43);status.ForeColor=Visual.Muted;help=ButtonAt(30,458,52,(s,e)=>Process.Start("https://github.com/JunyanKang/paper-voice/blob/main/docs/INSTALL"+(zh?"":".en")+".md"));language=ButtonAt(91,458,110,(s,e)=>{zh=!zh;RefreshText();});only=ButtonAt(301,458,116,(s,e)=>{if(complete&&xpi!=null){Process.Start("explorer.exe","/select,"+Setup.Quote(xpi));return;}Start(true);});cancel=ButtonAt(301,458,116,(s,e)=>{engine.Cancel();cancel.Enabled=false;status.Text=T("正在取消，已下载文件留待重试。","Cancelling. Verified downloads will be kept.");});cancel.Visible=false;action=ButtonAt(425,458,185,(s,e)=>{if(complete){ContinuePlugin();return;}Start(false);});action.BackColor=accent;action.ForeColor=Color.White;AcceptButton=action;RefreshText();FormClosing+=(s,e)=>{if(busy)e.Cancel=true;};Shown+=(s,e)=>{if(Setup.Flag("--progress-preview")||Setup.Arg("--preview-state")=="progress"){Busy(true);UpdateProgress("pluginDone",1);UpdateProgress("runtimeDone",1);UpdateProgress("voices",.42);}
 if(new[]{"complete","installed","running","multiple","missing"}.Contains(Setup.Arg("--preview-state"))){string state=Setup.Arg("--preview-state");complete=true;UpdateProgress("pluginDone",1);UpdateProgress("runtimeDone",1);UpdateProgress("voicesDone",1);UpdateProgress("ready",1);zoteroApp=state=="missing"?null:@"C:\Program Files\Zotero\zotero.exe";zoteroProfile=new[]{"multiple","missing"}.Contains(state)?null:new ZoteroProfile("default",Path.Combine(ZoteroInstall.ProfileBase,"Profiles","example.default"));didStage=new[]{"complete","installed"}.Contains(state);pluginState=state=="complete"?"pending":state;RefreshPluginUI();}
 if(Setup.Arg("--preview-state")=="error"){action.Text=T("重试","Retry");status.Text=T("下载未完成，请检查网络后重试。已有声音会保留。","Download interrupted. Check your connection and retry. Existing voices are kept.");}
 if(Setup.Arg("--visual-report")!=null)WriteVisualReport(Setup.Arg("--visual-report"));string shot=Setup.Arg("--screenshot");if(shot!=null){var timer=new System.Windows.Forms.Timer{Interval=600};timer.Tick+=(a,b)=>{timer.Stop();using(var bmp=new Bitmap(ClientSize.Width,ClientSize.Height)){using(var full=new Bitmap(Width,Height)){DrawToBitmap(full,new Rectangle(0,0,Width,Height));using(var g=Graphics.FromImage(bmp)){var origin=PointToScreen(Point.Empty);g.DrawImage(full,-(origin.X-Left),-(origin.Y-Top));}}bmp.Save(shot);}timer.Dispose();busy=false;Close();};timer.Start();}};
 }
 IEnumerable<Control> Descendants(Control parent){foreach(Control c in parent.Controls){yield return c;foreach(var child in Descendants(c))yield return child;}}
 void WriteVisualReport(string destination){string probe=(string)Visual.Appearance["glyphProbe"];var fonts=new[]{Visual.Font(12),Visual.Font(12,FontStyle.Bold)};var labels=Descendants(this).Where(c=>c is Label||c is PathDisplay).Select(c=>new {text=c.Text,font=c.Font.Name,size=c.Font.Size,covered=Visual.Covered(c.Font,c.Text),frame=new[]{PointToClient(c.PointToScreen(Point.Empty)).X,PointToClient(c.PointToScreen(Point.Empty)).Y,c.Width,c.Height}}).ToArray();var result=new{platform="Windows",language=zh?"zh":"en",state=Setup.Arg("--preview-state")??"idle",fonts=fonts.Select(f=>new{name=f.Name,probe=probe,covered=Visual.Covered(f,probe)}).ToArray(),labels=labels,width=ClientSize.Width,height=ClientSize.Height};File.WriteAllText(destination,new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(result));foreach(var font in fonts)font.Dispose();}
 void UpdateProgress(string phase,double value){int index=phase.StartsWith("plugin")?0:phase.StartsWith("runtime")?1:2;if(new[]{"plugin","runtime","voices"}.Contains(phase)){bars[index].Value=value;var a=index==0?(Dictionary<string,object>)Setup.Config["plugin"]:Setup.Packages[index==1?1:0];double total=Convert.ToDouble(a["bytes"]);badges[index].Text=string.Format("{0:F0}%",value*100);details[index].Text=T("下载中","Downloading")+string.Format(" · {0:F1} / {1:F1} MB",value*total/1e6,total/1e6);status.Text=T("下载完成后将校验文件并配置声音。","Files are verified before voice setup.");}else if(phase.EndsWith("Done")){bars[index].Value=1;bars[index].Tint=Visual.Green;badges[index].Text=T("✓ 已下载","✓ Ready");details[index].Text=T("文件已校验","Download verified");}else if(phase.EndsWith("Extract")){details[index].Text=T("正在解压…","Unpacking…");}else if(phase=="verify"){status.Text=T("正在检查声音文件…","Checking voice files…")+string.Format(" {0:F0}%",value*100);}else if(phase=="reused"){for(int i=1;i<3;i++){bars[i].Value=1;bars[i].Tint=Visual.Green;badges[i].Text=T("✓ 已有","✓ Found");details[i].Text=T("已校验，跳过下载","Verified · No download needed");}}else if(phase=="setup"){cancel.Enabled=false;status.Text=T("正在验证声音可用性并完成安装…","Checking voices and finishing setup…");}else if(phase=="ready"){for(int i=1;i<3;i++){badges[i].Text=T("✓ 已就绪","✓ Ready");details[i].Text=T("声音已安装，可以离线听读","Installed · Ready for offline listening");}}}
 void PreparePlugin(){zoteroApp=ZoteroInstall.Applications().FirstOrDefault();var profiles=ZoteroInstall.Profiles(ZoteroInstall.ProfileBase);zoteroProfile=profiles.Count==1?profiles[0]:null;RefreshPluginUI();if(zoteroApp!=null&&zoteroProfile!=null)ContinuePlugin();pluginTimer=new System.Windows.Forms.Timer{Interval=1000};pluginTimer.Tick+=(s,e)=>{if(!complete)return;if(!didStage){if(zoteroApp==null)zoteroApp=ZoteroInstall.Applications().FirstOrDefault();if(zoteroProfile==null){var profilesNow=ZoteroInstall.Profiles(ZoteroInstall.ProfileBase);if(profilesNow.Count==1)zoteroProfile=profilesNow[0];}}if(pluginState=="running"&&!ZoteroInstall.Running())ContinuePlugin();if(didStage&&zoteroProfile!=null){var asset=(Dictionary<string,object>)Setup.Config["plugin"];pluginState=ZoteroInstall.Status(zoteroProfile.Path,(string)Setup.Config["version"],(string)asset["sha256"]);RefreshPluginUI();}};pluginTimer.Start();}
 void RefreshPluginUI(){target.Text="Zotero";path.Text=zoteroProfile!=null?zoteroProfile.Name:T("选择用户配置","Select a profile");browse.Text=T("选择配置","Profile");only.Text=T("手动安装","Manual install");if(zoteroApp==null){action.Text=T("选择 Zotero","Locate Zotero");status.Text=T("未找到 Zotero 10。请选择应用，或先安装并打开一次。","Zotero 10 not found. Locate it, or install and open it once.");return;}if(zoteroProfile==null){action.Text=T("选择配置","Select profile");status.Text=T("请选择要安装的用户配置；首次使用请先打开 Zotero 一次。","Choose a profile. First-time users: open Zotero once.");return;}action.Text=didStage?T("打开 Zotero","Open Zotero"):T("继续安装","Continue install");if(pluginState=="installed"){badges[0].Text=T("✓ 已安装","✓ Installed");details[0].Text=T("插件已启用，可以使用","Plugin enabled and ready");status.Text=T("安装完成。打开 Zotero 即可开始听读。","Setup complete. Open Zotero to start listening.");}else if(didStage){badges[0].Text=T("待启用","Enable in Zotero");details[0].Text=T("已放置并校验插件","Plugin placed and verified");status.Text=pluginState=="incompatible"?T("Zotero 暂不能启用此版本，请检查兼容性。","Zotero cannot enable this version. Check compatibility."):T("打开 Zotero → 工具 → 插件，启用 Paper Voice。","Open Zotero → Tools → Plugins. Enable Paper Voice.");}else if(pluginState=="running"){status.Text=T("请先正常退出 Zotero，安装器会自动继续。","Quit Zotero normally. Setup will continue automatically.");}else if(pluginState!="error"){status.Text=T("将安装到所选配置；已有设置会保留。","Install into this profile. Existing settings are kept.");}}
 void ChooseProfile(){var profiles=ZoteroInstall.Profiles(ZoteroInstall.ProfileBase);if(profiles.Count>1){using(var dialog=new Form{Text=T("选择 Zotero 配置","Choose a Zotero profile"),ClientSize=new Size(500,156),FormBorderStyle=FormBorderStyle.FixedDialog,StartPosition=FormStartPosition.CenterParent,MinimizeBox=false,MaximizeBox=false,BackColor=Visual.Paper,Font=Visual.Font(12)}){var label=new SmoothLabel{Text=T("仅安装到所选配置，其他配置保持不变。","Only the selected profile will receive the plugin."),Location=new Point(20,16),Size=new Size(460,26),ForeColor=Visual.Ink,UseCompatibleTextRendering=true};var select=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Location=new Point(20,48),Size=new Size(460,30),Font=Visual.Font(12)};select.Items.AddRange(profiles.Cast<object>().ToArray());select.SelectedIndex=0;var choose=new QuietButton{Text=T("选择","Choose"),Location=new Point(374,105),Size=new Size(106,34),BackColor=accent,ForeColor=Color.White,DialogResult=DialogResult.OK};var other=new QuietButton{Text=T("其他位置…","Browse…"),Location=new Point(254,105),Size=new Size(110,34),BackColor=Color.White,DialogResult=DialogResult.Retry};var cancelChoice=new QuietButton{Text=T("取消","Cancel"),Location=new Point(20,105),Size=new Size(80,34),BackColor=Color.White,DialogResult=DialogResult.Cancel};dialog.Controls.AddRange(new Control[]{label,select,choose,other,cancelChoice});dialog.AcceptButton=choose;dialog.CancelButton=cancelChoice;var result=dialog.ShowDialog(this);if(result==DialogResult.OK)zoteroProfile=(ZoteroProfile)select.SelectedItem;else if(result==DialogResult.Retry){if(!PickProfile())return;}else return;}}else if(!PickProfile())return;didStage=false;pluginState="";RefreshPluginUI();if(zoteroApp!=null)ContinuePlugin();}
 bool PickProfile(){using(var picker=new FolderBrowserDialog{Description=T("选择含 prefs.js 的 Zotero 配置目录","Choose a Zotero profile containing prefs.js"),SelectedPath=ZoteroInstall.ProfileBase,ShowNewFolderButton=false}){if(picker.ShowDialog(this)==DialogResult.OK){if(ZoteroInstall.ValidProfile(picker.SelectedPath)){zoteroProfile=new ZoteroProfile(Path.GetFileName(picker.SelectedPath),picker.SelectedPath);return true;}else status.Text=T("这不是 Zotero 配置目录。请选择含 prefs.js 的目录。","Choose a Zotero profile containing prefs.js.");}}return false;}
 void ContinuePlugin(){if(zoteroApp==null){using(var picker=new OpenFileDialog{Title=T("选择 Zotero 10","Locate Zotero 10"),Filter="Zotero|zotero.exe",CheckFileExists=true}){if(picker.ShowDialog(this)==DialogResult.OK&&ZoteroInstall.ValidApp(picker.FileName))zoteroApp=picker.FileName;}RefreshPluginUI();if(zoteroApp!=null&&zoteroProfile!=null)ContinuePlugin();return;}if(zoteroProfile==null){ChooseProfile();return;}if(didStage){try{if(!ZoteroInstall.Running())ZoteroInstall.Launch(zoteroApp,zoteroProfile.Path);else status.Text=T("请在 Zotero → 工具 → 插件中启用 Paper Voice。","Enable Paper Voice in Zotero → Tools → Plugins.");}catch(Exception e){status.Text=e.Message;}return;}if(ZoteroInstall.Running()){pluginState="running";RefreshPluginUI();return;}if(xpi==null)return;try{var asset=(Dictionary<string,object>)Setup.Config["plugin"];pluginState=ZoteroInstall.Stage(xpi,zoteroProfile.Path,(string)Setup.Config["version"],(string)asset["sha256"],Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"PaperVoiceInstaller","plugin-backups"));didStage=true;RefreshPluginUI();}catch(Exception e){pluginState="error";RefreshPluginUI();status.Text=e.Message;}}
 void Busy(bool value){busy=value;action.Enabled=only.Enabled=browse.Enabled=language.Enabled=!value;cancel.Visible=value;only.Visible=!value;cancel.Enabled=true;}
 async void Start(bool pluginOnly){Busy(true);complete=false;didStage=false;pluginState="";if(pluginTimer!=null)pluginTimer.Stop();engine=new Engine();engine.Progress=(p,v)=>BeginInvoke(new Action(()=>UpdateProgress(p,v)));try{xpi=await Task.Run(()=>engine.Install(root,Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"PaperVoiceInstaller"),Setup.Pointer,pluginOnly));complete=true;PreparePlugin();}catch(Exception e){action.Text=T("重试","Retry");status.Text=engine.Cancelled?T("已取消。原有声音保留，可继续下载。","Cancelled. Existing voices kept; retry to continue."):T("未完成：","Not completed: ")+e.Message;}finally{Busy(false);engine.Dispose();engine=null;}}
}
