using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.Win32;

internal sealed class ZoteroProfile {internal string Name,Path;internal ZoteroProfile(string name,string path){Name=name;Path=path;}public override string ToString(){return Name+" — "+Path;}}
internal static class ZoteroInstall {
 internal const string AddonID="paper-voice@local.research";
 internal static string ProfileBase{get{return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"Zotero","Zotero");}}
 internal static List<Dictionary<string,string>> Ini(string path){var rows=new List<Dictionary<string,string>>();var row=new Dictionary<string,string>();if(!File.Exists(path))return rows;foreach(string raw in File.ReadAllLines(path)){string line=raw.Trim().TrimStart('\ufeff');if(line.Length==0||line.StartsWith(";")||line.StartsWith("#"))continue;if(line.StartsWith("[")&&line.EndsWith("]")){if(row.Count>0)rows.Add(row);row=new Dictionary<string,string>{{"section",line.Substring(1,line.Length-2)}};}else{int eq=line.IndexOf('=');if(eq>0)row[line.Substring(0,eq).Trim()]=line.Substring(eq+1).Trim();}}if(row.Count>0)rows.Add(row);return rows;}
 internal static bool ValidProfile(string path){return Directory.Exists(path)&&(File.Exists(Path.Combine(path,"prefs.js"))||File.Exists(Path.Combine(path,"times.json")));}
 internal static List<ZoteroProfile> Profiles(string folder){var profiles=new List<ZoteroProfile>();var seen=new HashSet<string>(StringComparer.OrdinalIgnoreCase);foreach(var row in Ini(Path.Combine(folder,"profiles.ini"))){string section,path,relative,name;if(!row.TryGetValue("section",out section)||!section.StartsWith("Profile")||!row.TryGetValue("Path",out path)||path.Length==0)continue;row.TryGetValue("IsRelative",out relative);if(relative!="1"&&!Path.IsPathRooted(path))continue;try{path=Path.GetFullPath(relative=="1"?Path.Combine(folder,path):path);if(ValidProfile(path)&&seen.Add(path))profiles.Add(new ZoteroProfile(row.TryGetValue("Name",out name)?name:Path.GetFileName(path),path));}catch(ArgumentException){}catch(NotSupportedException){}}return profiles;}
 internal static bool ValidApp(string path){try{if(!File.Exists(path)||!string.Equals(Path.GetFileName(path),"zotero.exe",StringComparison.OrdinalIgnoreCase))return false;var info=FileVersionInfo.GetVersionInfo(path);if((info.ProductName??"").IndexOf("Zotero",StringComparison.OrdinalIgnoreCase)<0)return false;var folder=Path.GetDirectoryName(path);var rows=Ini(Path.Combine(folder,"application.ini")).Concat(Ini(Path.Combine(folder,"app","application.ini")));return rows.Any(r=>r.ContainsKey("Name")&&r["Name"]=="Zotero"&&r.ContainsKey("Version")&&r["Version"].StartsWith("10."));}catch{return false;}}
 internal static List<string> Applications(){var found=new List<string>();foreach(var p in Process.GetProcessesByName("zotero")){try{found.Add(p.MainModule.FileName);}catch{}finally{p.Dispose();}}foreach(var hive in new[]{RegistryHive.CurrentUser,RegistryHive.LocalMachine})foreach(var view in new[]{RegistryView.Registry64,RegistryView.Registry32})try{using(var root=RegistryKey.OpenBaseKey(hive,view)){using(var key=root.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\App Paths\zotero.exe")){if(key!=null)found.Add(Convert.ToString(key.GetValue(null)));}using(var keys=root.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Uninstall")){if(keys!=null)foreach(var name in keys.GetSubKeyNames())using(var key=keys.OpenSubKey(name)){if(key==null||!Convert.ToString(key.GetValue("DisplayName")).StartsWith("Zotero",StringComparison.OrdinalIgnoreCase))continue;string loc=Convert.ToString(key.GetValue("InstallLocation"));if(loc.Length>0)found.Add(Path.Combine(loc,"zotero.exe"));string icon=Convert.ToString(key.GetValue("DisplayIcon"));if(icon.Length>0)found.Add(icon.Split(',')[0].Trim('"'));}}}}catch{}foreach(var folder in new[]{Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles),Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86),Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)})if(folder.Length>0)found.Add(Path.Combine(folder,"Zotero","zotero.exe"));return found.Where(p=>!string.IsNullOrEmpty(p)&&ValidApp(p)).Distinct(StringComparer.OrdinalIgnoreCase).ToList();}
 internal static bool Running(){var processes=Process.GetProcessesByName("zotero");bool running=processes.Length>0;foreach(var p in processes)p.Dispose();return running;}
 static void NotLinked(string path){if((File.Exists(path)||Directory.Exists(path))&&(File.GetAttributes(path)&FileAttributes.ReparsePoint)!=0)throw new IOException("目录包含链接，请手动安装 / Linked directory: install manually");}
 internal static Dictionary<string,object> Metadata(string profile){try{var db=Setup.Parse(File.ReadAllText(Path.Combine(profile,"extensions.json")));return Setup.Rows(db["addons"]).FirstOrDefault(a=>Convert.ToString(a["id"])==AddonID);}catch{return null;}}
 static bool IsTrue(Dictionary<string,object> a,string key){object v;return a.TryGetValue(key,out v)&&v is bool&&(bool)v;}
 internal static string Status(string profile,string version,string digest){string target=Path.Combine(profile,"extensions",AddonID+".xpi");try{if(!File.Exists(target)||Setup.Hash(target)!=digest)return "missing";}catch{return "missing";}var addon=Metadata(profile);if(addon==null||Convert.ToString(addon["version"])!=version)return "pending";if(IsTrue(addon,"appDisabled"))return "incompatible";if(IsTrue(addon,"userDisabled")||IsTrue(addon,"softDisabled"))return "disabled";return IsTrue(addon,"active")?"installed":"pending";}
 internal static string Stage(string xpi,string profile,string version,string digest,string backups){if(!ValidProfile(profile))throw new IOException("请选择 Zotero 配置目录 / Choose a Zotero profile");if(Setup.Hash(xpi)!=digest)throw new IOException("插件校验失败 / Plugin verification failed");string lockPath=Path.Combine(profile,"parent.lock");NotLinked(lockPath);FileStream profileLock;try{profileLock=new FileStream(lockPath,FileMode.OpenOrCreate,FileAccess.ReadWrite,FileShare.None);}catch(IOException){throw new IOException("请先退出 Zotero，再继续 / Quit Zotero, then continue");}using(profileLock){string extensions=Path.Combine(profile,"extensions");NotLinked(extensions);Directory.CreateDirectory(extensions);string target=Path.Combine(extensions,AddonID+".xpi");NotLinked(target);if(Directory.Exists(Path.Combine(extensions,AddonID))||File.Exists(Path.Combine(extensions,AddonID)))throw new IOException("检测到开发版插件，请手动安装 / Development copy found: install manually");if(File.Exists(target)){if(Setup.Hash(target)==digest)return Status(profile,version,digest);var previous=Metadata(profile);if(previous!=null){Version installed,next;if(Version.TryParse(Convert.ToString(previous["version"]),out installed)&&Version.TryParse(version,out next)&&installed>next)throw new IOException("已安装更新版本 / A newer version is installed");}Directory.CreateDirectory(backups);string backup=Path.Combine(backups,Guid.NewGuid().ToString("N")+".xpi");File.Copy(target,backup);if(Setup.Hash(backup)!=Setup.Hash(target))throw new IOException("备份校验失败 / Backup verification failed");}string temp=Path.Combine(extensions,".paper-voice-"+Guid.NewGuid().ToString("N"));try{File.Copy(xpi,temp);if(Setup.Hash(temp)!=digest)throw new IOException("插件校验失败 / Plugin verification failed");string startup=Path.Combine(profile,"addonStartup.json.lz4");NotLinked(startup);if(File.Exists(startup)){Directory.CreateDirectory(backups);File.Copy(startup,Path.Combine(backups,Guid.NewGuid().ToString("N")+"-addonStartup.json.lz4"));File.Delete(startup);}if(File.Exists(target))File.Replace(temp,target,null);else File.Move(temp,target);if(Setup.Hash(target)!=digest)throw new IOException("插件校验失败 / Plugin verification failed");return "pending";}finally{if(File.Exists(temp))File.Delete(temp);}}}
 internal static void Launch(string application,string profile){if(!ValidApp(application)||!ValidProfile(profile))throw new IOException("未找到 Zotero 10 / Zotero 10 not found");Process.Start(new ProcessStartInfo(application,"-profile "+Setup.Quote(profile)){UseShellExecute=false});}
}
